version: "3.8"

services:
  navakij-ua-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navakij-ua-app
    volumes:
      - ./navakijwebsite:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - navakij-ua-db
    expose:
      - "9000"
    networks:
      - nginx_proxy
      - navakij_internal

  navakij-ua-nginx:
    image: nginx:latest
    container_name: navakij-ua-nginx
    volumes:
      - ./navakijwebsite:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - navakij-ua-app
    expose:
      - "80"
    networks:
      - nginx_proxy
      - navakij_internal

  navakij-ua-db:
    image: mysql:5.6
    container_name: navakij-ua-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: navakij_db
      MYSQL_USER: navakij_db
      MYSQL_PASSWORD: F8tq93pWz4BcKdX2
    volumes:
      - navakij_uat_db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"  # Optional: expose for manual access
    networks:
      - navakij_internal

volumes:
  navakij_uat_db_data:

networks:
  nginx_proxy:
    external: true
  navakij_internal:
    driver: bridge
